---
- name: apt update and apt upgrade
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
        dpkg_options: 'force-confdef,force-confold'
        
# Servers should be restarted sequientally to avoid etcd learner issues
# Agents have no such limitation
- name: Upgrade K3s Servers
  hosts: server
  become: true
  serial: 1
  roles:
    - role: k3s_upgrade

- name: Upgrade K3s Agents
  hosts: agent
  become: true
  roles:
    - role: k3s_upgrade

